spring.datasource.url=jdbc:postgresql://localhost:5432/Travel_Stories
spring.datasource.username=postgres
spring.datasource.password=Orio@123

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=50MB

# Root logging
logging.level.root=INFO

# Your application
logging.level.org.travel_stories=DEBUG

# Frameworks
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN

# SQL (enable only when debugging)
# logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.hibernate.orm.jdbc.bind=TRACE